# Generated by Django 5.1.7 on 2026-04-25 12:53

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='especialidad',
            name='unique_descripcion',
        ),
        migrations.RenameIndex(
            model_name='especialidad',
            new_name='idx_esp_desc_is_deleted',
            old_name='idex_descripcion_is_deleted',
        ),
        migrations.RunSQL(
            sql="UPDATE especialidad_especialidad SET descripcion = '' WHERE descripcion IS NULL",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='descripcion',
            field=models.CharField(help_text='Descripción de la especialidad', max_length=150),
        ),
        migrations.AddConstraint(
            model_name='especialidad',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('descripcion'), condition=models.Q(('is_deleted', False)), name='unique_especialidad_descripcion'),
        ),
        migrations.AlterModelTable(
            name='especialidad',
            table='especialidad',
        ),
    ]
