# Generated by Django 5.1.7 on 2026-04-11 22:32

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('descripcion', models.CharField(help_text='Nombre descriptivo del tipo de documento (ej: Historia Clínica, Receta)', max_length=100)),
                ('storage_key', models.SlugField(help_text='Clave de almacenamiento para rutas de archivos. Solo minúsculas, números y guiones bajos.')),
                ('id_usu_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('id_usu_modificator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de documento digitalizado',
                'verbose_name_plural': 'Tipos de documento digitalizado',
                'db_table': 'tipo_doc_dig',
                'ordering': ['descripcion'],
                'indexes': [models.Index(fields=['descripcion', 'is_deleted'], name='idx_tipo_doc_dig_desc_del')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('descripcion'), condition=models.Q(('is_deleted', False)), name='unique_tipo_doc_dig_descripcion'), models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('storage_key',), name='unique_tipo_doc_dig_storage_key')],
            },
        ),
    ]
