# Generated by Django 5.1.7 on 2026-04-12 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('horario_prestador', '0002_especialidad_fk_to_m2m'),
        ('paciente', '0005_move_pacienteresponsable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('fecha', models.DateField(help_text='Fecha del turno')),
                ('hora_desde', models.TimeField(help_text='Hora de inicio del turno')),
                ('hora_hasta', models.TimeField(help_text='Hora de fin del turno')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado'), ('inactivo', 'Inactivo'), ('cancelado', 'Cancelado')], default='disponible', help_text='Estado actual del turno', max_length=12)),
                ('observacion', models.TextField(blank=True, help_text='Observaciones del turno', null=True)),
                ('horario_prestador', models.ForeignKey(help_text='Horario del prestador al que pertenece este turno', on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='horario_prestador.horarioprestador')),
                ('id_usu_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('id_usu_modificator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(blank=True, help_text='Paciente asignado (null si el turno está disponible)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos', to='paciente.paciente')),
            ],
            options={
                'verbose_name': 'Agenda',
                'verbose_name_plural': 'Agenda',
                'db_table': 'agenda',
                'ordering': ['fecha', 'hora_desde'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('horario_prestador', 'fecha', 'hora_desde'), name='unique_agenda_turno')],
            },
        ),
    ]
