# Generated by Django 5.1.7 on 2026-04-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado'), ('inactivo', 'Inactivo'), ('cancelado', 'Cancelado'), ('realizado', 'Realizado')], default='disponible', help_text='Estado actual del turno', max_length=12),
        ),
    ]
