# Generated by Django 5.1.7 on 2026-04-21 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_add_realizado_estado'),
        ('pago_prestador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='pagado_prestador',
            field=models.BooleanField(default=False, help_text='True cuando este turno fue incluido en un pago al prestador'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='pago_prestador',
            field=models.ForeignKey(blank=True, help_text='Referencia al pago al prestador que incluye este turno', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos', to='pago_prestador.pagoprestador'),
        ),
    ]
