# Stage 1: compilar React
FROM node:22-alpine AS build

WORKDIR /app
COPY package*.json .
RUN npm ci --legacy-peer-deps
COPY . .
RUN npm run build

# Stage 2: servir los estáticos con Nginx
FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80 443
