# Generated by Django 5.1.7 on 2026-03-07 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacienteResponsable',
            fields=[
                ('id_usu_creator', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_usu_modificator', models.IntegerField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('parentesco', models.CharField(help_text='Parentesco del paciente responsable con el paciente', max_length=200)),
                ('persona', models.ForeignKey(help_text='Persona a la que se le asigna el paciente responsable', on_delete=django.db.models.deletion.PROTECT, related_name='paciente_responsable', to='persona.persona')),
            ],
            options={
                'verbose_name': 'Paciente Responsable',
                'verbose_name_plural': 'Pacientes Responsables',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_usu_creator', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_usu_modificator', models.IntegerField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_nacimiento', models.DateField(help_text='Fecha de nacimiento del paciente')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], help_text='Sexo del paciente', max_length=1)),
                ('observacion', models.CharField(blank=True, help_text='Observaciones adicionales sobre el paciente', max_length=5000, null=True)),
                ('persona', models.ForeignKey(help_text='Persona a la que se le asigna el paciente', on_delete=django.db.models.deletion.PROTECT, related_name='paciente', to='persona.persona')),
                ('responsable', models.ForeignKey(blank=True, help_text='Paciente responsable del paciente', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paciente_responsable', to='paciente.pacienteresponsable')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.AddIndex(
            model_name='pacienteresponsable',
            index=models.Index(fields=['persona'], name='idx_pac_resp_per'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['persona'], name='idx_paciente_persona'),
        ),
        migrations.AddConstraint(
            model_name='paciente',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('persona',), name='unique_paciente_persona'),
        ),
    ]
