@startuml 01_login_logout

<style>
sequenceDiagram {
  LifeLine {
    LineStyle solid
    LineThickness 1
    LineColor black
  }
}
</style>

skinparam monochrome true
skinparam shadowing false
skinparam backgroundColor white
skinparam sequenceArrowThickness 1
skinparam defaultFontName Arial
skinparam defaultFontSize 11

autoactivate on

actor USUARIO

boundary "GUI_login" as LOGIN
control "VIEWS" as AUTH

== 1. Login exitoso ==

USUARIO --> LOGIN : ingresa usuario y contrasena
USUARIO --> LOGIN : ingresa password
USUARIO --> LOGIN : Boton iniciar sesion
LOGIN --> AUTH : Envia datos (POST)
AUTH --> AUTH : Autenticar(username, password)
return
return Usuario autenticado y activo / ingreso al sistema
return Redirige a 'inicio'

== 2. Credenciales incorrectas ==

USUARIO --> LOGIN : ingresa credenciales invalidas
LOGIN --> AUTH : Envia datos (POST)
return acceso denegado
return 'Nombre de usuario o contrasena incorrectos'

== 3. Cuenta inactiva ==

USUARIO --> LOGIN : credenciales validas / cuenta inactiva
LOGIN --> AUTH : Envia datos (POST)
return acceso denegado
return Muestra error 'Tu cuenta esta inactiva'

== 4. Cerrar sesion ==

USUARIO --> LOGIN : Boton cerrar sesion
LOGIN --> AUTH : logout()
return sesion cerrada
return Redirige a 'iniciarSesion'

@enduml
