@startuml
!theme plain

<style>
sequenceDiagram {
  LifeLine {
    LineStyle solid
    LineThickness 1
    LineColor black
  }
}
</style>

actor Usuario
boundary GUI_Login as Login
control AuthController as Auth

== Login exitoso ==

Usuario --> Login : Ingresa usuario
activate Login
Usuario --> Login : Ingresa contraseña
Usuario --> Login : Boton ingresar
Login --> Auth : POST login
activate Auth
Auth --> Auth : Validar credenciales

Auth --> Login : Login correcto
deactivate Auth
Login --> Usuario : Mostrar inicio
deactivate Login
== Credenciales incorrectas ==

Usuario -> Login : Ingresa datos inválidos
Login -> Auth : POST login

Auth --> Login : Error autenticación
Login --> Usuario : Usuario o contraseña incorrectos

== Cuenta inactiva ==

Usuario -> Login : Ingresa credenciales
Login -> Auth : POST login

Auth --> Login : Cuenta inactiva
Login --> Usuario : Tu cuenta está inactiva

== Logout ==

Usuario -> Login : Cerrar sesión
Login -> Auth : logout()

Auth --> Login : Sesión cerrada
Login --> Usuario : Mostrar login

@enduml
