# Generated by Django 5.1.7 on 2026-04-14 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultas', '0001_initial'),
        ('paciente', '0005_move_pacienteresponsable'),
        ('tipo_doc_dig', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoDigPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('storage', models.TextField(help_text='Ruta relativa desde /media/')),
                ('filename', models.TextField(help_text='Nombre original del archivo')),
                ('consulta', models.ForeignKey(blank=True, help_text='Consulta a la que pertenece este documento (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='consultas.consulta')),
                ('id_usu_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('id_usu_modificator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(help_text='Paciente al que pertenece este documento', on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='paciente.paciente')),
                ('tipo_doc_dig', models.ForeignKey(help_text='Tipo de documento digitalizado', on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='tipo_doc_dig.tipodocdigital')),
            ],
            options={
                'verbose_name': 'Documento digitalizado del paciente',
                'verbose_name_plural': 'Documentos digitalizados de pacientes',
                'db_table': 'documento_dig_paciente',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
