# Generated by Django 5.1.7 on 2026-05-11 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
        ('persona_rrhh', '0004_alter_personarrhh_honorario_and_more'),
        ('tipo_doc_dig', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoDigPrestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('storage', models.TextField(help_text='Ruta relativa desde /media/')),
                ('filename', models.TextField(help_text='Nombre original del archivo')),
                ('id_usu_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('id_usu_modificator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('persona_rrhh', models.ForeignKey(help_text='Prestador al que pertenece este documento', on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='persona_rrhh.personarrhh')),
                ('tipo_doc_dig', models.ForeignKey(help_text='Tipo de documento digitalizado', on_delete=django.db.models.deletion.PROTECT, related_name='documentos_prestador', to='tipo_doc_dig.tipodocdigital')),
            ],
            options={
                'verbose_name': 'Documento digitalizado del prestador',
                'verbose_name_plural': 'Documentos digitalizados de prestadores',
                'db_table': 'documento_dig_prestador',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
