# Generated by Django 5.1.7 on 2026-04-21 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona_rrhh', '0002_personarrhh_honorario'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='medico_asignado',
            field=models.ForeignKey(blank=True, help_text='Médico al que asiste esta secretaria', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretarias', to='persona_rrhh.personarrhh'),
        ),
    ]
