# Generated by Django 5.1.7 on 2026-04-19 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forma_pago', '0002_insertar_formas_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='formapago',
            name='tipo',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
    ]
