# Generated by Django 5.1.7 on 2026-04-03 16:53

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoClinico',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_evento', models.CharField(help_text='Tipo de evento clínico (por ejemplo, consulta, cirugía, etc.)', max_length=50)),
                ('id_usu_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('id_usu_modificator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento Clínico',
                'verbose_name_plural': 'Eventos Clínicos',
                'ordering': ['tipo_evento'],
                'indexes': [models.Index(fields=['tipo_evento', 'is_deleted'], name='idx_tipo_evento_is_deleted')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('tipo_evento'), condition=models.Q(('is_deleted', False)), name='unique_tipo_evento')],
            },
        ),
    ]
