# Generated by Django 5.1.7 on 2026-04-21 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona_rrhh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personarrhh',
            name='honorario',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto de honorario referencial del prestador', max_digits=14, null=True),
        ),
    ]
