# Generated by Django 5.1.7 on 2026-03-30 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiaSemana',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(help_text='Ejemplo: Lunes, Martes, Miércoles, etc.', max_length=20)),
                ('abreviatura', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': 'Día de la semana',
                'verbose_name_plural': 'Días de la semana',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['descripcion'], name='idx_diasemana_descripcion')],
            },
        ),
    ]
