# Generated by Django 5.1.7 on 2026-04-14 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0002_add_realizado_estado'),
        ('eventoclinico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('hora_desde', models.TimeField(blank=True, help_text='Hora de inicio efectivo de la consulta', null=True)),
                ('hora_hasta', models.TimeField(blank=True, help_text='Hora de fin efectivo de la consulta', null=True)),
                ('estado', models.CharField(choices=[('en_espera', 'En espera'), ('en_consulta', 'En consulta'), ('finalizada', 'Finalizada')], default='en_espera', help_text='Estado actual de la consulta', max_length=12)),
                ('motivo_consulta', models.TextField(blank=True, help_text='Motivo de consulta referido por el paciente', null=True)),
                ('diagnostico', models.TextField(blank=True, help_text='Diagnóstico del médico', null=True)),
                ('tratamiento', models.TextField(blank=True, help_text='Tratamiento indicado', null=True)),
                ('indicaciones', models.TextField(blank=True, help_text='Indicaciones y recomendaciones', null=True)),
                ('proxima_cita', models.DateField(blank=True, help_text='Fecha sugerida para la próxima cita', null=True)),
                ('agenda', models.ForeignKey(help_text='Turno de agenda asociado a esta consulta', on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='agenda.agenda')),
                ('evento_clinico', models.ForeignKey(blank=True, help_text='Tipo de evento clínico de esta consulta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas', to='eventoclinico.eventoclinico')),
                ('id_usu_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('id_usu_modificator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'db_table': 'consulta',
                'ordering': ['-agenda__fecha', 'hora_desde'],
            },
        ),
    ]
