# Generated by Django 5.1.7 on 2026-05-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='estado',
            field=models.CharField(choices=[('en_espera', 'En espera'), ('en_consulta', 'En consulta'), ('finalizada', 'Finalizada'), ('anulada', 'Anulada')], default='en_espera', help_text='Estado actual de la consulta', max_length=12),
        ),
    ]
