# Generated by Django 5.1.7 on 2026-04-01 00:34

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultorio',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nro_consultorio', models.CharField(help_text='Nro del consultorio', max_length=50)),
                ('descripcion', models.CharField(help_text='Descripción del consultorio', max_length=150)),
                ('id_usu_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('id_usu_modificator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consultorio',
                'verbose_name_plural': 'Consultorios',
                'ordering': ['nro_consultorio'],
                'indexes': [models.Index(fields=['nro_consultorio', 'is_deleted'], name='idx_consultorio_nro_is_deleted')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('nro_consultorio'), condition=models.Q(('is_deleted', False)), name='unique_nro_consultorio')],
            },
        ),
    ]
