# Generated by Django 5.1.7 on 2026-04-19 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caja_banco', '0001_initial'),
        ('forma_pago', '0004_poblar_tipo_forma_pago'),
        ('persona', '0004_alter_persona_options_alter_tipodocumento_options'),
        ('productos', '0001_initial'),
        ('timbrado', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaFactCab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('fecha', models.DateField(help_text='Fecha de emisión de la factura')),
                ('condicion_vta', models.BooleanField(default=True, help_text='True = Contado, False = Crédito')),
                ('observacion', models.TextField(blank=True, default='')),
                ('nro_comprobante', models.IntegerField(null=True)),
                ('grav_5', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('grav_10', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('iva_5', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('iva_10', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_gravada', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_iva', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('vuelto', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('id_usu_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('id_usu_modificator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='persona.persona')),
                ('timbrado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='timbrado.timbrado')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'venta_fact_cab',
                'ordering': ['-fecha', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='CtaCobrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('nro_cuota', models.PositiveIntegerField()),
                ('cant_cuota', models.PositiveIntegerField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('monto_cuota', models.DecimalField(decimal_places=2, max_digits=18)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('vencido', 'Vencido')], default='pendiente', max_length=20)),
                ('id_usu_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('id_usu_modificator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('vfc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='facturacion.ventafactcab')),
            ],
            options={
                'verbose_name': 'Cuota a cobrar',
                'verbose_name_plural': 'Cuotas a cobrar',
                'db_table': 'cta_cobrar',
                'ordering': ['vfc', 'nro_cuota'],
            },
        ),
        migrations.CreateModel(
            name='VentaFactDet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=18)),
                ('monto', models.DecimalField(decimal_places=2, help_text='Total de la línea', max_digits=18)),
                ('impuesto', models.CharField(help_text='Copiado del producto al guardar — histórico', max_length=10)),
                ('exento', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('sub_gra_5', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('sub_gra_10', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('sub_iva_5', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('sub_iva_10', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('id_usu_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('id_usu_modificator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('prs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fact_detalle', to='productos.productoservicio')),
                ('vfc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='facturacion.ventafactcab')),
            ],
            options={
                'verbose_name': 'Ítem de factura',
                'verbose_name_plural': 'Ítems de factura',
                'db_table': 'venta_fact_det',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VentaFactDetCobranza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('voucher', models.CharField(blank=True, default='', max_length=100)),
                ('nro_comprobante', models.CharField(blank=True, default='', max_length=100)),
                ('cta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fact_cobranza', to='caja_banco.cuentamcb')),
                ('forma_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fact_cobranza', to='forma_pago.formapago')),
                ('id_usu_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('id_usu_modificator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('vfc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobranza', to='facturacion.ventafactcab')),
            ],
            options={
                'verbose_name': 'Cobranza de factura',
                'verbose_name_plural': 'Cobranzas de factura',
                'db_table': 'venta_fact_det_cobranza',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='ventafactcab',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('timbrado', 'nro_comprobante'), name='unique_fact_timbrado_nro'),
        ),
    ]
