# Generated by Django 5.1.7 on 2026-04-18 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0002_add_realizado_estado'),
        ('consultas', '0001_initial'),
        ('paciente', '0005_move_pacienteresponsable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('recordatorio_cita', 'Recordatorio de cita'), ('confirmacion_reserva', 'Confirmación de reserva'), ('indicaciones', 'Indicaciones'), ('otro', 'Otro')], max_length=25)),
                ('canal', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('manual', 'Manual')], max_length=10)),
                ('estado', models.CharField(choices=[('enviado', 'Enviado'), ('fallido', 'Fallido'), ('pendiente', 'Pendiente')], default='pendiente', max_length=10)),
                ('mensaje', models.TextField(help_text='Texto enviado al paciente')),
                ('destinatario', models.CharField(help_text='Email o teléfono al momento del envío', max_length=254)),
                ('fecha_envio', models.DateTimeField(blank=True, help_text='Fecha y hora efectiva del envío', null=True)),
                ('agenda', models.ForeignKey(blank=True, help_text='Turno de agenda relacionado (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='agenda.agenda')),
                ('consulta', models.ForeignKey(blank=True, help_text='Consulta relacionada (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='consultas.consulta')),
                ('id_usu_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('id_usu_modificator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(help_text='Paciente destinatario de la notificación', on_delete=django.db.models.deletion.PROTECT, related_name='notificaciones', to='paciente.paciente')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificacion',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
