# Generated by Django 5.1.7 on 2026-05-19 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_remitente', models.EmailField(default='noreply@clinicalichi.com', max_length=254)),
                ('nombre_remitente', models.CharField(default='Clínica Lichi', max_length=100)),
                ('habilitado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'notificacion_configuracion',
            },
        ),
        migrations.CreateModel(
            name='PlantillaNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('recordatorio', 'Recordatorio de cita'), ('confirmacion', 'Confirmación de reserva'), ('cancelacion', 'Cancelación'), ('post_consulta', 'Post consulta')], max_length=15)),
                ('asunto', models.CharField(max_length=200)),
                ('cuerpo', models.TextField(help_text='Variables disponibles: {nombre}, {fecha}, {hora}, {medico}, {especialidad}, {indicaciones}')),
                ('activa', models.BooleanField(default=True)),
                ('id_usu_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('id_usu_modificator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plantilla de notificación',
                'verbose_name_plural': 'Plantillas de notificación',
                'db_table': 'notificacion_plantilla',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('tipo',), name='unique_plantilla_tipo_activa')],
            },
        ),
    ]
