# Generated by Django 5.1.7 on 2026-05-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_configuracionnotificacion_plantillanotificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionnotificacion',
            name='auto_cancelacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracionnotificacion',
            name='auto_confirmacion',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracionnotificacion',
            name='auto_recordatorio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracionnotificacion',
            name='horas_anticipacion',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AddField(
            model_name='configuracionnotificacion',
            name='horas_anticipacion_2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
