# Generated by Django 5.1.7 on 2026-04-19 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caja_banco', '0001_initial'),
        ('estadocuenta', '0001_initial'),
        ('forma_pago', '0004_poblar_tipo_forma_pago'),
        ('persona', '0004_alter_persona_options_alter_tipodocumento_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobranza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('comprobante_nro', models.IntegerField(null=True)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('vuelto', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('id_usu_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('id_usu_modificator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobranzas', to='persona.persona')),
            ],
            options={
                'verbose_name': 'Cobranza',
                'verbose_name_plural': 'Cobranzas',
                'db_table': 'cobranza',
                'ordering': ['-fecha', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='CobranzaDet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=18)),
                ('nro_comprobante', models.CharField(blank=True, default='', max_length=200)),
                ('cobranza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='cobranzas.cobranza')),
                ('cta_cobrar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobros', to='estadocuenta.ctacobrar')),
                ('id_usu_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('id_usu_modificator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalle de cobranza',
                'verbose_name_plural': 'Detalles de cobranza',
                'db_table': 'cobranza_det',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ValorRecibidoCob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('voucher', models.CharField(blank=True, default='', max_length=100)),
                ('nro_comprobante', models.CharField(blank=True, default='', max_length=100)),
                ('cobranza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_recibidos', to='cobranzas.cobranza')),
                ('cta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobranza_valores', to='caja_banco.cuentamcb')),
                ('forma_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobranza_valores', to='forma_pago.formapago')),
                ('id_usu_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('id_usu_modificator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Valor recibido en cobranza',
                'verbose_name_plural': 'Valores recibidos en cobranza',
                'db_table': 'valor_recibido_cob',
                'ordering': ['id'],
            },
        ),
    ]
