# Generated by Django 5.1.7 on 2026-04-18 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Timbrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('nro_timbrado', models.CharField(help_text='Número de timbrado (hasta 8 dígitos numéricos)', max_length=8)),
                ('inicio_vigencia', models.DateField(help_text='Fecha de inicio de vigencia del timbrado')),
                ('fin_vigencia', models.DateField(help_text='Fecha de fin de vigencia del timbrado')),
                ('punto_sucursal', models.CharField(help_text='Punto de sucursal (ej: 001)', max_length=3)),
                ('punto_expedicion', models.CharField(help_text='Punto de expedición (ej: 001)', max_length=3)),
                ('nro_desde', models.PositiveIntegerField(help_text='Número de comprobante inicial')),
                ('nro_hasta', models.PositiveIntegerField(help_text='Número de comprobante final')),
                ('autoimpresor', models.BooleanField(default=False, help_text='True si es autoimpresor (impresora fiscal), False si es talonario')),
                ('nro_habilitacion', models.CharField(blank=True, help_text='Número de habilitación SET (solo talonario)', max_length=50)),
                ('id_usu_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('id_usu_modificator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Timbrado',
                'verbose_name_plural': 'Timbrados',
                'db_table': 'timbrado',
                'ordering': ['-inicio_vigencia'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('nro_timbrado',), name='unique_timbrado_nro')],
            },
        ),
    ]
