# Generated by Django 5.1.7 on 2026-03-25 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_rename_ciudad_persona_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'ordering': ['nro_documento'], 'verbose_name': 'Persona', 'verbose_name_plural': 'Personas'},
        ),
        migrations.AlterModelOptions(
            name='tipodocumento',
            options={'ordering': ['descripcion'], 'verbose_name': 'Tipo de Documento', 'verbose_name_plural': 'Tipos de Documentos'},
        ),
    ]
