# Generated by Django 5.1.7 on 2026-04-19 00:15

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaMcb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('descripcion', models.CharField(help_text='Nombre de la cuenta (caja, banco, etc.)', max_length=150)),
                ('id_usu_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('id_usu_modificator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuenta Caja/Banco',
                'verbose_name_plural': 'Cuentas Caja/Banco',
                'db_table': 'cuenta_mcb',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCajaBanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('vfdc_id', models.IntegerField(blank=True, help_text='TODO: FK → VentaFactCab', null=True)),
                ('vrc_id', models.IntegerField(blank=True, help_text='TODO: FK → ValorRecibidoCob', null=True)),
                ('ppdc_id', models.IntegerField(blank=True, help_text='TODO: FK → PagoPrestadorDetCobranza', null=True)),
                ('fecha', models.DateField(default=datetime.date.today, help_text='Fecha del movimiento')),
                ('voucher', models.CharField(blank=True, help_text='Número de voucher o referencia', max_length=50, null=True)),
                ('monto_ingreso', models.DecimalField(decimal_places=2, default=0, help_text='Monto de ingreso', max_digits=18)),
                ('monto_egreso', models.DecimalField(decimal_places=2, default=0, help_text='Monto de egreso', max_digits=18)),
                ('vuelto', models.DecimalField(decimal_places=2, default=0, help_text='Vuelto entregado', max_digits=18)),
                ('cta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='caja_banco.cuentamcb', verbose_name='Cuenta')),
                ('id_usu_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('id_usu_modificator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento Caja/Banco',
                'verbose_name_plural': 'Movimientos Caja/Banco',
                'db_table': 'movimiento_caja_banco',
                'ordering': ['-fecha', '-fecha_creacion'],
            },
        ),
        migrations.AddConstraint(
            model_name='cuentamcb',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('descripcion',), name='unique_cuenta_mcb_descripcion'),
        ),
    ]
