# Generated by Django 5.1.7 on 2026-05-05 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente_responsable', '0002_db_table_y_unique'),
        ('persona', '0006_persona_fecha_nacimiento_alter_persona_ciudad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacienteresponsable',
            name='grupo_sanguineo',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('desconocido', 'Desconocido')], max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='pacienteresponsable',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pacienteresponsable',
            name='persona',
            field=models.ForeignKey(help_text='Persona vinculada como responsable', on_delete=django.db.models.deletion.PROTECT, related_name='paciente_responsable', to='persona.persona'),
        ),
        migrations.RunSQL(
            sql='CREATE INDEX IF NOT EXISTS "idx_pac_resp_per" ON "paciente_responsable" ("persona_id");',
            reverse_sql='DROP INDEX IF EXISTS "idx_pac_resp_per";',
        ),
    ]
