# Generated by Django 5.1.7 on 2026-04-19 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('descripcion', models.CharField(help_text='Nombre del grupo de productos/servicios', max_length=150)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el grupo está activo')),
                ('id_usu_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('id_usu_modificator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'db_table': 'grupo_producto',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='ProductoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('descripcion', models.CharField(help_text='Nombre o descripción del producto/servicio', max_length=200)),
                ('impuesto', models.CharField(choices=[('10', 'IVA 10%'), ('5', 'IVA 5%'), ('exenta', 'Exenta')], default='10', help_text='Tipo de impuesto aplicable', max_length=10)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el producto/servicio está activo')),
                ('grupo', models.ForeignKey(help_text='Grupo al que pertenece el producto/servicio', on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='productos.grupo')),
                ('id_usu_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('id_usu_modificator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Producto/Servicio',
                'verbose_name_plural': 'Productos/Servicios',
                'db_table': 'producto_servicio',
                'ordering': ['descripcion'],
            },
        ),
        migrations.AddConstraint(
            model_name='grupo',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('descripcion',), name='unique_grupo_descripcion_activo'),
        ),
    ]
