# Generated by Django 5.1.7 on 2026-05-06 02:00

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='grupo',
            name='unique_grupo_descripcion_activo',
        ),
        migrations.AddConstraint(
            model_name='grupo',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('descripcion'), condition=models.Q(('is_deleted', False)), name='unique_grupo_descripcion_lower'),
        ),
        migrations.AddConstraint(
            model_name='productoservicio',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('descripcion'), models.F('grupo'), condition=models.Q(('is_deleted', False)), name='unique_prod_descripcion_grupo_lower'),
        ),
    ]
