# Generated by Django 5.1.7 on 2026-04-25 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventoclinico', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='eventoclinico',
            new_name='idx_evento_clinico_is_deleted',
            old_name='idx_tipo_evento_is_deleted',
        ),
        migrations.AlterModelTable(
            name='eventoclinico',
            table='evento_clinico',
        ),
    ]
