# Generated by Django 5.1.7 on 2026-04-12 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('especialidad', '0001_initial'),
        ('persona', '0004_alter_persona_options_alter_tipodocumento_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaRRHH',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_nacimiento', models.DateField(blank=True, help_text='Fecha de nacimiento del prestador', null=True)),
                ('fecha_ingreso', models.DateField(blank=True, help_text='Fecha de ingreso a la institución', null=True)),
                ('nro_matricula', models.CharField(blank=True, help_text='Número de matrícula profesional', max_length=50, null=True)),
                ('cargo', models.CharField(choices=[('medico', 'Médico'), ('enfermero', 'Enfermero/a'), ('administrativo', 'Administrativo'), ('tecnico', 'Técnico'), ('otro', 'Otro')], help_text='Cargo del prestador', max_length=20)),
                ('tipo_contrato', models.CharField(choices=[('dependencia', 'Dependencia'), ('honorarios', 'Honorarios'), ('eventual', 'Eventual')], help_text='Tipo de contrato', max_length=20)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('licencia', 'Licencia')], default='activo', help_text='Estado del prestador', max_length=10)),
                ('observacion', models.TextField(blank=True, help_text='Observaciones adicionales', null=True)),
                ('especialidades', models.ManyToManyField(blank=True, help_text='Especialidades del prestador', related_name='prestadores', to='especialidad.especialidad')),
                ('id_usu_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('id_usu_modificator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('persona', models.ForeignKey(help_text='Persona asociada al prestador', on_delete=django.db.models.deletion.PROTECT, related_name='persona_rrhh', to='persona.persona')),
            ],
            options={
                'verbose_name': 'Persona RRHH',
                'verbose_name_plural': 'Personas RRHH',
                'db_table': 'persona_rrhh',
                'ordering': ['persona__nro_documento'],
                'indexes': [models.Index(fields=['persona'], name='idx_rrhh_persona')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('persona',), name='unique_rrhh_persona')],
            },
        ),
    ]
