# Generated by Django 5.1.7 on 2026-05-02 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidad', '0002_rename_table_and_fix_descripcion'),
        ('persona', '0006_persona_fecha_nacimiento_alter_persona_ciudad_and_more'),
        ('persona_rrhh', '0002_personarrhh_honorario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personarrhh',
            name='fecha_nacimiento',
        ),
        migrations.AlterField(
            model_name='personarrhh',
            name='cargo',
            field=models.CharField(choices=[('medico', 'Médico'), ('enfermero', 'Enfermero/a'), ('administrativo', 'Administrativo'), ('tecnico', 'Técnico'), ('otro', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='personarrhh',
            name='especialidades',
            field=models.ManyToManyField(blank=True, related_name='prestadores', to='especialidad.especialidad'),
        ),
        migrations.AlterField(
            model_name='personarrhh',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('licencia', 'Licencia')], default='activo', max_length=10),
        ),
        migrations.AlterField(
            model_name='personarrhh',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personarrhh',
            name='honorario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='personarrhh',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='personarrhh',
            name='nro_matricula',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personarrhh',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personarrhh',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='persona_rrhh', to='persona.persona'),
        ),
        migrations.AlterField(
            model_name='personarrhh',
            name='tipo_contrato',
            field=models.CharField(choices=[('dependencia', 'Dependencia'), ('honorarios', 'Honorarios'), ('eventual', 'Eventual')], max_length=20),
        ),
    ]
