# Generated by Django 5.1.7 on 2026-05-05 01:55

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidad', '0002_rename_table_and_fix_descripcion'),
        ('persona', '0006_persona_fecha_nacimiento_alter_persona_ciudad_and_more'),
        ('persona_rrhh', '0003_remove_personarrhh_fecha_nacimiento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='personarrhh',
            name='honorario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='personarrhh',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('nro_matricula__isnull', False)), fields=('nro_matricula',), name='unique_rrhh_nro_matricula'),
        ),
    ]
