# Generated by Django 5.1.7 on 2026-04-21 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caja_banco', '0001_initial'),
        ('forma_pago', '0004_poblar_tipo_forma_pago'),
        ('persona_rrhh', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoPrestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_pago', models.DateField()),
                ('monto_hora', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_hora', models.DecimalField(decimal_places=2, max_digits=18)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=18)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('pagado', 'Pagado')], default='pendiente', max_length=50)),
                ('id_usu_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('id_usu_modificator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('persona_rrhh', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='persona_rrhh.personarrhh')),
            ],
            options={
                'verbose_name': 'Pago a prestador',
                'verbose_name_plural': 'Pagos a prestadores',
                'db_table': 'pago_prestador',
                'ordering': ['-fecha_pago', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PagoPrestadorDetCobranza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('voucher', models.CharField(blank=True, default='', max_length=100)),
                ('cta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pago_prestador_det', to='caja_banco.cuentamcb')),
                ('forma_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pago_prestador_det', to='forma_pago.formapago')),
                ('id_usu_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('id_usu_modificator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('pago_prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_cobranza', to='pago_prestador.pagoprestador')),
            ],
            options={
                'verbose_name': 'Detalle cobranza pago prestador',
                'verbose_name_plural': 'Detalles cobranza pagos prestadores',
                'db_table': 'pago_prestador_det_cobranza',
                'ordering': ['id'],
            },
        ),
    ]
