# Generated by Django 5.1.7 on 2026-05-26 02:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago_prestador', '0001_initial'),
        ('persona_rrhh', '0004_alter_personarrhh_honorario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoprestador',
            name='nro_comprobante',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='pagoprestador',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('nro_comprobante__isnull', False)), fields=('nro_comprobante',), name='unique_pago_prestador_nro_activo'),
        ),
    ]
