MODULOS = {
    # Administración
    'Persona':              'Administración',
    'PerfilUsuario':        'Administración',
    'PersonaRRHH':          'Administración',
    'TipoDocumento':        'Administración',
    # Clínica
    'Paciente':             'Clínica',
    'PacienteResponsable':  'Clínica',
    'Consultorio':          'Clínica',
    'Especialidad':         'Clínica',
    'EventoClinico':        'Clínica',
    'HorarioPrestador':     'Clínica',
    'Agenda':               'Clínica',
    'Consulta':             'Clínica',
    'DocumentoDigPaciente': 'Clínica',
    'DocumentoDigPrestador': 'Clínica',
    # Facturación
    'VentaFactCab':         'Facturación',
    'Timbrado':             'Facturación',
    'ProductoServicio':     'Facturación',
    'Grupo':                'Facturación',
    # Finanzas
    'CuentaMcb':            'Finanzas',
    'MovimientoCajaBanco':  'Finanzas',
    'Cobranza':             'Finanzas',
    'PagoPrestador':        'Finanzas',
    # Mantenimiento
    'Pais':                 'Mantenimiento',
    'Departamento':         'Mantenimiento',
    'Ciudad':               'Mantenimiento',
    'TipoDocDigital':       'Mantenimiento',
    # Notificaciones
    'notificacion':         'Notificaciones',
}
