# Generated by Django 5.1.7 on 2026-04-25 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0002_alter_consultorio_descripcion'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='consultorio',
            table='consultorio',
        ),
    ]
