# Generated by Django 5.1.7 on 2026-03-07 16:54

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ubicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id_usu_creator', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_usu_modificator', models.IntegerField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(help_text='Descripción del tipo de documento', max_length=200)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documentos',
                'indexes': [models.Index(django.db.models.functions.text.Lower('descripcion'), name='idx_tipo_doc_descripcion')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('descripcion'), name='unique_tipo_documento_descripcion')],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_usu_creator', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_usu_modificator', models.IntegerField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nro_documento', models.CharField(help_text='Número del documento de la persona', max_length=50)),
                ('ruc_dv', models.IntegerField(blank=True, help_text='Dígito verificador del RUC (opcional)', null=True)),
                ('razon_social', models.CharField(help_text='Razón social de la persona', max_length=400)),
                ('telefono', models.CharField(blank=True, help_text='Número de teléfono de la persona (opcional)', max_length=20, null=True)),
                ('correo_electronico', models.EmailField(blank=True, help_text='Correo electrónico de la persona (opcional)', max_length=254, null=True)),
                ('direccion', models.CharField(blank=True, help_text='Dirección de la persona (opcional)', max_length=200, null=True)),
                ('Ciudad', models.ForeignKey(blank=True, help_text='Ciudad de residencia de la persona', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personas', to='ubicacion.ciudad')),
                ('Departamento', models.ForeignKey(blank=True, help_text='Departamento de residencia de la persona', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personas', to='ubicacion.departamento')),
                ('Pais', models.ForeignKey(blank=True, help_text='País de residencia de la persona', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personas', to='ubicacion.pais')),
                ('tipo_documento', models.ForeignKey(help_text='Tipo de documento asociado a la persona', on_delete=django.db.models.deletion.PROTECT, related_name='personas', to='persona.tipodocumento')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'indexes': [models.Index(django.db.models.functions.text.Lower('nro_documento'), models.F('razon_social'), name='idx_per_nro_doc_tip_doc')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('nro_documento'), condition=models.Q(('is_deleted', False)), name='unique_persona_nro_documento')],
            },
        ),
    ]
