# Generated by Django 5.1.7 on 2026-03-14 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_alter_persona_id_usu_creator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='Ciudad',
            new_name='ciudad',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='Departamento',
            new_name='departamento',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='Pais',
            new_name='pais',
        ),
    ]
