# Generated by Django 5.1.7 on 2026-03-07 16:54

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_usu_creator', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_usu_modificator', models.IntegerField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(help_text='Descripción del país', max_length=200)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'ordering': ['descripcion'],
                'indexes': [models.Index(fields=['descripcion', 'is_deleted'], name='idx_pais_desc_is_deleted')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('descripcion'), condition=models.Q(('is_deleted', False)), name='unique_pais_descripcion')],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_usu_creator', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_usu_modificator', models.IntegerField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(help_text='Descripción del departamento', max_length=200)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departamentos', to='ubicacion.pais')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_usu_creator', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_usu_modificator', models.IntegerField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(help_text='Descripción de la ciudad', max_length=200)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ciudades', to='ubicacion.departamento')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'ordering': ['descripcion'],
                'indexes': [models.Index(fields=['descripcion', 'is_deleted'], name='idx_ciu_desc_is_deleted')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('descripcion'), models.F('departamento'), condition=models.Q(('is_deleted', False)), name='unique_ciudad_descripcion_departamento')],
            },
        ),
        migrations.AddIndex(
            model_name='departamento',
            index=models.Index(fields=['descripcion', 'is_deleted'], name='idx_dep_desc_is_deleted'),
        ),
        migrations.AddConstraint(
            model_name='departamento',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('descripcion'), models.F('pais'), condition=models.Q(('is_deleted', False)), name='unique_departamento_descripcion_pais'),
        ),
    ]
