# Generated by Django 5.1.7 on 2026-04-25 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubicacion', '0002_alter_ciudad_id_usu_creator_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ciudad',
            table='ciudad',
        ),
        migrations.AlterModelTable(
            name='departamento',
            table='departamento',
        ),
        migrations.AlterModelTable(
            name='pais',
            table='pais',
        ),
    ]
