# Generated by Django 5.1.7 on 2026-04-01 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultorio',
            name='descripcion',
            field=models.CharField(blank=True, help_text='Descripción del consultorio', max_length=150, null=True),
        ),
    ]
