# Generated by Django 5.1.7 on 2026-04-12 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diasemana', '0002_insertar_dias_semana'),
        ('especialidad', '0001_initial'),
        ('persona_rrhh', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioPrestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('hora_desde', models.TimeField(help_text='Hora de inicio de atención')),
                ('hora_hasta', models.TimeField(help_text='Hora de fin de atención')),
                ('intervalo', models.PositiveIntegerField(choices=[(15, '15 min'), (20, '20 min'), (30, '30 min'), (45, '45 min'), (60, '60 min')], default=30, help_text='Duración de cada turno en minutos')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('excepcion', models.BooleanField(default=False, help_text='Si True, el horario aplica solo en la fecha puntual indicada')),
                ('fecha_excepcion', models.DateField(blank=True, help_text='Fecha puntual (obligatoria si excepcion=True)', null=True)),
                ('dia_semana', models.ForeignKey(help_text='Día de la semana (se auto-asigna si es excepción)', on_delete=django.db.models.deletion.PROTECT, related_name='horarios', to='diasemana.diasemana')),
                ('especialidad', models.ForeignKey(blank=True, help_text='Especialidad con la que atiende en este horario', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='horarios', to='especialidad.especialidad')),
                ('id_usu_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('id_usu_modificator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('persona_rrhh', models.ForeignKey(help_text='Prestador al que pertenece el horario', on_delete=django.db.models.deletion.PROTECT, related_name='horarios', to='persona_rrhh.personarrhh')),
            ],
            options={
                'verbose_name': 'Horario Prestador',
                'verbose_name_plural': 'Horarios Prestador',
                'db_table': 'horario_prestador',
                'ordering': ['persona_rrhh', 'dia_semana__id', 'hora_desde'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('excepcion', False), ('is_deleted', False)), fields=('persona_rrhh', 'dia_semana', 'hora_desde'), name='unique_horario_prestador')],
            },
        ),
    ]
