# Generated by Django 5.1.7 on 2026-04-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidad', '0001_initial'),
        ('horario_prestador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horarioprestador',
            name='especialidad',
        ),
        migrations.AddField(
            model_name='horarioprestador',
            name='especialidades',
            field=models.ManyToManyField(blank=True, help_text='Especialidades que se atienden en este horario', related_name='horarios', to='especialidad.especialidad'),
        ),
    ]
