# Generated by Django 5.1.7 on 2026-03-25 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_alter_paciente_id_usu_creator_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['persona__nro_documento'], 'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AlterModelOptions(
            name='pacienteresponsable',
            options={'ordering': ['persona__nro_documento'], 'verbose_name': 'Paciente Responsable', 'verbose_name_plural': 'Pacientes Responsables'},
        ),
        migrations.AddField(
            model_name='paciente',
            name='alergias_conocidas',
            field=models.TextField(blank=True, help_text='Alergias conocidas del paciente', null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='enfermedades_cronicas',
            field=models.TextField(blank=True, help_text='Enfermedades cronicas del paciente', null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='grupo_sanguineo',
            field=models.CharField(blank=True, help_text='Grupo sanguineo del paciente', max_length=10, null=True),
        ),
    ]
