# Generated by Django 5.1.7 on 2026-03-27 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_alter_paciente_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacienteresponsable',
            name='parentesco',
        ),
        migrations.AddField(
            model_name='paciente',
            name='parentesco',
            field=models.CharField(blank=True, help_text='Parentesco con el paciente responsable', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pacienteresponsable',
            name='es_contacto_emergencia',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pacienteresponsable',
            name='grupo_sanguineo',
            field=models.CharField(blank=True, help_text='Grupo sanguineo del paciente responsable', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pacienteresponsable',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pacienteresponsable',
            name='ocupacion',
            field=models.CharField(blank=True, help_text='Ocupación del paciente responsable', max_length=150, null=True),
        ),
    ]
