# Generated by Django 5.1.7 on 2026-05-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0007_remove_paciente_fecha_nacimiento_alter_paciente_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='grupo_sanguineo',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('desconocido', 'Desconocido')], help_text='Grupo sanguineo del paciente', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='observacion',
            field=models.TextField(blank=True, help_text='Observaciones adicionales sobre el paciente', null=True),
        ),
    ]
